# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'WeiBoDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeiBoDemo
  pod 'SnapKit', '~>3.1.2'
  pod 'Alamofire', '~>4.3.0'
  pod 'SVProgressHUD', '~>2.1.2'
  pod 'SDWebImage', '~>4.0.0-beta2'
  pod 'SDWebImage/GIF', '~>4.0.0-beta2'
  pod 'MJRefresh', '~>3.1.12'
  pod 'FLAnimatedImage', '~>1.0.12'

end
